AWSTemplateFormatVersion: "2010-09-09"
Description: AWS EC2 Instance with a Security Group

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0  # Specify the AMI ID for your region
      KeyName: MyKeyPair  # Ensure that the key pair exists in your account
      SecurityGroups:
        - Ref: MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  # Open SSH to the world (replace for better security)
          
Outputs:
  InstanceId:
    Description: "Instance ID"
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp
